### ISSUE TITLE
Errors after deleting temporary files: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Steff02** [kevinsung/slp-to-video#8]
`Dumping video frames and audio...
1/1
Merging video and audio...
1/1
{ [Error: ENOENT: no such file or directory, unlink '/tmp/tmp-7f4e4406b154877a1ddfdf19/tmp-0459438876467905df3e738e/0.avi']
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path:
   '/tmp/tmp-7f4e4406b154877a1ddfdf19/tmp-0459438876467905df3e738e/0.avi' }
`
This seems to be some kind of issue with the order that the temporary files are deleted/unlinked as there are lines which use the directories after they've been deleted.

**Comment by Steff02** [comment]
Error: ENOTEMPTY: directory not empty, rmdir '/tmp/tmp-81c211b1112bebcc745a3795'
    at Object.rmdirSync (fs.js:684:3)
    at process.on (/home/steff/Desktop/SLPVID/slp-to-video/slp_to_video.js:449:35)
    at process.emit (events.js:198:13)

this is also relevant

**Comment by kevinsung** [comment]
@Steff02 sorry for the delayed response, this is fixed in a4cf6de
